### ISSUE TITLE
Allow people to select an event image by URL.

### ISSUE THREAD

**Issue by profan** [fparma/events#10]
Right now it's just file upload for event images, allow people to also select the image for the event through specifying an URL.

**Comment by Cuel** [comment]
Just an input type text for URL that would be sent when the event is submitted?

**Comment by profan** [comment]
Yeah, exactly like that

**Comment by Cuel** [comment]
Yep just won't be any checks if it's an actual image? I guess

**Comment by profan** [comment]
Yeah, we won't do any validation, should be fine without it though
